# # Use a lightweight Python base image
# FROM python:3.11-slim

# # Set the working directory
# WORKDIR /credit_app

# # Copy the requirements file and install dependencies
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy the application code
# COPY app.py .
# EXPOSE 6051

# # Command to run the application with Gunicorn
# CMD ["gunicorn", "--bind", "0.0.0.0:6051", "app:app"]


# Use a lightweight Python base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /credit_app

# Install system dependencies needed for mysqlclient
RUN apt-get update && apt-get install -y \
    python3-dev \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY app.py .
EXPOSE 6051

# Command to run the application with Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:6051", "app:app"]
