# Use a lightweight Python base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /Stream

# Install FFmpeg 
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY stream.py .
EXPOSE 6050

# Command to run the application with Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:6050", "stream:app"]
