# Generated by Django 5.0.8 on 2024-12-22 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_nvr_options_anprstatus_cameraid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anprstatus",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="cameraalerts",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="cameraalertstatuss",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="cameraiplists",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="cameras",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="groups",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="numberplatedetections",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="nvr",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="readedvehiclenoplates",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="roles",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="vehicledetections",
            options={"managed": False, "ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="videoanalytics",
            options={"managed": False, "ordering": ["-id"]},
        ),
    ]
