# Generated by Django 5.0.8 on 2024-12-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_cameraactivities_cameraid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nvr",
            options={"managed": False},
        ),
        migrations.AddField(
            model_name="anprstatus",
            name="cameraid",
            field=models.ForeignKey(
                db_column="CameraId",
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.cameras",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="anprstatus",
            name="userid",
            field=models.ForeignKey(
                db_column="UserId",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.users",
            ),
            preserve_default=False,
        ),
    ]
