# Use a lightweight Python base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /Stream

# Install FFmpeg 
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


ENV STREAM_API="https://14.195.152.244:7007"

# Copy the application code
COPY StreamProvider.py .
EXPOSE 7015

# Command to run the application with Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:7015", "StreamProvider:app"]
