#!/bin/sh

# Write env.js file dynamically from runtime ENV vars
cat <<EOF > /usr/share/nginx/html/env.js
window._env_ = {
  REACT_APP_API_URL: "${REACT_APP_API_URL}",
  REACT_APP_CREDIT_API_URL: "${REACT_APP_CREDIT_API_URL}",
  REACT_APP_STREAM_API_URL: "${REACT_APP_STREAM_API_URL}",
  REACT_APP_LIVE_FEED_URL: "${REACT_APP_LIVE_FEED_URL}",
  REACT_APP_VIDEO_API_URL: "${REACT_APP_VIDEO_API_URL}",
  REACT_APP_STREAM_URL: "${REACT_APP_STREAM_URL}",
  REACT_APP_ONVIF_URL: "${REACT_APP_ONVIF_URL}",
  REACT_APP_ADDCAMERA_URL: "${REACT_APP_ADDCAMERA_URL}",
  REACT_APP_DETECTION_URL: "${REACT_APP_DETECTION_URL}",
  REACT_APP_ANPR_API_URL: "${REACT_APP_ANPR_API_URL}"
};
EOF

exec nginx -g "daemon off;"
