# Use the official Nginx image as a base
FROM nginx:latest

# Remove the default configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx config file into the container
COPY nginx.conf /etc/nginx/conf.d/

# Expose port 80 for the reverse proxy
EXPOSE 6053
