
# Stage 1: Build stage
FROM python:3.12-alpine AS builder
WORKDIR /app
COPY requirements.txt .
RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev && \
    pip install --no-cache-dir -r requirements.txt --target /install

# Stage 2: Final lightweight image
FROM python:3.12-alpine
WORKDIR /app
COPY --from=builder /install /app
COPY . .
CMD ["python", "anpr_api.py"]